services:
  - type: web
    name: abinoo
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn your_project_name.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"